import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { QueryProvider } from "@/lib/providers";
import { Toaster } from "sonner";
import { CategoryProvider } from "@/lib/context/category";
import { CartProvider, useCart } from "@/lib/context/cartContext";
import Header from "@/components/header";
import Category from "@/components/category/category";
import { GlobalStateProvider } from "@/lib/context/globalContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} w-full antialiased`}
      >
        {/* would have used redux for a much bigger state*/}

        <QueryProvider>
          <GlobalStateProvider>
            <CategoryProvider>
              <CartProvider>
                <Header />
                <div className="xl:flex px-6 space-y-6 xl:space-y-0 gap-8">
                  <Category />
                  <div className="flex-1 border rounded-xl shadow">
                    {children}
                  </div>
                </div>
              </CartProvider>
            </CategoryProvider>
          </GlobalStateProvider>

          <Toaster richColors />
        </QueryProvider>
      </body>
    </html>
  );
}
